version: '3'
services:
  pushgateway:
    image: prom/pushgateway:v0.4.0
    ports:
      - 9091:9091
    networks:
      - compose_seacloudserver

  prometheus:
    image: prom/prometheus:v2.0.0
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts/:/etc/prometheus/rules.d/
    networks:
      - compose_seacloudserver

  grafana:
    image: grafana/grafana:10.1.10
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - compose_seacloudserver

  alertmanager:
    image: prom/alertmanager:v0.11.0
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - compose_seacloudserver

networks:
  compose_seacloudserver:
    external: true
